[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
]

[project]
name = "allianceauth-gf-conman"
description = ""
readme = "README.md"
keywords = [
    "allianceauth",
]
license = { file = "LICENSE" }
authors = [  ]
requires-python = ">=3.10"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dynamic = [
    "version",
]
dependencies = [
    "allianceauth<6,>=5",
    "allianceauth-corptools>=2.5.5",
    "allianceauth-invoices>=0.1.7",
    "allianceauth-georgeforge>=0.6.3",
    "py-cord<3,>=2",
    "django-eveonline-sde>=0.0.1a1,<1",
]

dev = [
    "django-stubs"
]

[tool.hatch.version]
path = "gf_conman/__init__.py"

[tool.hatch.build]
include = [ "/gf_conman" ]
