# Generated by Django 5.2.16 on 2026-07-30 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('gf_conman', '0001_initial'), ('gf_conman', '0002_contractfilter_monitoredcontract'), ('gf_conman', '0003_webhook_remove_contractfilter_webhook_url_and_more'), ('gf_conman', '0004_alter_contractfilter_color'), ('gf_conman', '0005_webhook_description_webhook_username_and_more'), ('gf_conman', '0006_remove_webhook_ping_id_remove_webhook_role_ping_and_more'), ('gf_conman', '0007_remove_contractfilter_color')]

    dependencies = [
        ('corptools', '0008_bpc_me_te_runs'),
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ContractFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the filter', max_length=255, verbose_name='Name')),
                ('gf_integration', models.BooleanField(default=False, verbose_name='GeorgeForge Integration')),
                ('color', models.CharField(blank=True, default='', help_text='Optional color for embed on Discord - #000000 / black means no color selected.', max_length=7, verbose_name='Embed Color')),
                ('description_filter', models.TextField(blank=True, help_text='Filter contracts by description (case insensitive)', null=True, verbose_name='Description Filter')),
                ('from_character', models.ForeignKey(blank=True, help_text='Filter contracts from this character', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_filters_from_character', to='eveonline.evecharacter')),
                ('from_corporation', models.ForeignKey(blank=True, help_text='Filter contracts from this corporation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_filters_from_corporation', to='eveonline.evecorporationinfo')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonitoredContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_status', models.CharField(max_length=25)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_by', to='corptools.contract')),
                ('triggered_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_contracts', to='gf_conman.contractfilter')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('contract', 'triggered_filter')},
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to send the notification to', verbose_name='Webhook URL')),
                ('description', models.CharField(default='Default', help_text='Description of the webhook', max_length=255, verbose_name='Description')),
                ('username', models.CharField(default='ConMan', help_text='Username to send the notification as', max_length=80, verbose_name='Username')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='contractfilter',
            name='webhook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gf_conman.webhook'),
        ),
        migrations.AddField(
            model_name='contractfilter',
            name='ping_id',
            field=models.BigIntegerField(blank=True, help_text='Optional ID to ping on Discord', null=True, verbose_name='Ping ID'),
        ),
        migrations.AddField(
            model_name='contractfilter',
            name='role_ping',
            field=models.BooleanField(default=False, help_text='Is the Ping ID a role ID', verbose_name='Role Ping'),
        ),
        migrations.RemoveField(
            model_name='contractfilter',
            name='color',
        ),
    ]
