# Generated by Django 5.2.16 on 2026-07-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0008_bpc_me_te_runs'),
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('gf_conman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the filter', max_length=255, verbose_name='Name')),
                ('gf_integration', models.BooleanField(default=False, verbose_name='GeorgeForge Integration')),
                ('webhook_url', models.URLField(help_text='URL to send the notification to', verbose_name='Webhook URL')),
                ('color', models.CharField(blank=True, default='', help_text='Optional color for embed on Discord - #000000 / black means no color selected.', max_length=7, verbose_name='Embed Color')),
                ('description_filter', models.TextField(blank=True, help_text='Filter contracts by description (case insensitive)', null=True, verbose_name='Description Filter')),
                ('from_character', models.ForeignKey(blank=True, help_text='Filter contracts from this character', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_filters_from_character', to='eveonline.evecharacter')),
                ('from_corporation', models.ForeignKey(blank=True, help_text='Filter contracts from this corporation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_filters_from_corporation', to='eveonline.evecorporationinfo')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonitoredContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_status', models.CharField(max_length=25)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_by', to='corptools.contract')),
                ('triggered_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_contracts', to='gf_conman.contractfilter')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('contract', 'triggered_filter')},
            },
        ),
    ]
