# Generated by Django 5.2.16 on 2026-08-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('gf_conman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_by', to='eveonline.evecharacter')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
