# Generated by Django 5.2.16 on 2026-07-29 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf_conman', '0002_contractfilter_monitoredcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to send the notification to', verbose_name='Webhook URL')),
                ('ping_id', models.BigIntegerField(blank=True, help_text='Optional ID to ping on Discord', null=True, verbose_name='Ping ID')),
                ('role_ping', models.BooleanField(default=False, help_text='Is the `ping_id` a role ID', verbose_name='Role Ping')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='contractfilter',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='contractfilter',
            name='webhook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gf_conman.webhook'),
        ),
    ]
