# Generated by Django 5.2.16 on 2026-07-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf_conman', '0003_webhook_remove_contractfilter_webhook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractfilter',
            name='color',
            field=models.CharField(blank=True, default='#000000', help_text='Optional color for embed on Discord - #000000 / black means no color selected.', max_length=7, verbose_name='Embed Color'),
        ),
    ]
