# Generated by Django 5.2.16 on 2026-07-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf_conman', '0004_alter_contractfilter_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='description',
            field=models.CharField(default='Default', help_text='Description of the webhook', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhook',
            name='username',
            field=models.CharField(default='ConMan', help_text='Username to send the notification as', max_length=80, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webhook',
            name='role_ping',
            field=models.BooleanField(default=False, help_text='Is the Ping ID a role ID', verbose_name='Role Ping'),
        ),
    ]
