# Generated by Django 5.2.16 on 2026-07-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf_conman', '0005_webhook_description_webhook_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='ping_id',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='role_ping',
        ),
        migrations.AddField(
            model_name='contractfilter',
            name='ping_id',
            field=models.BigIntegerField(blank=True, help_text='Optional ID to ping on Discord', null=True, verbose_name='Ping ID'),
        ),
        migrations.AddField(
            model_name='contractfilter',
            name='role_ping',
            field=models.BooleanField(default=False, help_text='Is the Ping ID a role ID', verbose_name='Role Ping'),
        ),
    ]
