# Generated by Django 5.2.16 on 2026-07-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gf_conman', '0006_remove_webhook_ping_id_remove_webhook_role_ping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractfilter',
            name='color',
        ),
    ]
